package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.layout.Pane;
import javafx.scene.control.TableColumn;

public class AccountTransactionsAnchorPaneController implements Initializable {
	@FXML
	private Pane paneAccounts;
	@FXML
	private ComboBox<String> cbAccounts;
	@FXML
	private Button btnResetCBValue;
	@FXML
	private Label lblAccountBalance;
	@FXML
	private Label lblAccountBalanceValue;
	@FXML
	private TableView<String> tblAccounts;
	@FXML
	private TableColumn<String, String> tblClmSNo;
	@FXML
	private TableColumn<String, String> tblClmTID;
	@FXML
	private TableColumn<String, String> tblClmAccNo;
	@FXML
	private TableColumn<String, String> tblClmTName;
	@FXML
	private TableColumn<String, String> tblClmTType;
	@FXML
	private TableColumn<String, String> tblClmTDate;

	// Event Listener on ComboBox[#cbAccounts].onAction
	@FXML
	public void displayAccounts(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String selectedValue = cbAccounts.getSelectionModel().getSelectedItem();
		if(selectedValue != null) {
			btnResetCBValue.setVisible(true);
			lblAccountBalance.setVisible(true);
			lblAccountBalanceValue.setVisible(true);
			tblAccounts.setVisible(true);
		}
		System.out.println(selectedValue);
	}
	// Event Listener on Button[#btnResetCBValue].onAction
	@FXML
	public void clearSelectedValue(ActionEvent event) throws IOException {
		// TODO Autogenerated
		cbAccounts.getSelectionModel().clearSelection();
		cbAccounts.setButtonCell(new PromptButtonCell<>(cbAccounts.getPromptText()));
		lblAccountBalance.setVisible(false);
		lblAccountBalanceValue.setVisible(false);
		tblAccounts.setVisible(false);
		btnResetCBValue.setVisible(false);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		//List of account numbers of current user
		ObservableList<String> accountNumbersList = 
				FXCollections.observableArrayList("94467845362", "78546789012");
		
		cbAccounts.setItems(accountNumbersList);
		
		btnResetCBValue.setVisible(false);
		lblAccountBalance.setVisible(false);
		lblAccountBalanceValue.setVisible(false);
		tblAccounts.setVisible(false);
	}
}
