package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.input.InputMethodEvent;

public class AddNewBenAnchorPaneController {
	@FXML
	private TextField benName;
	@FXML
	private TextField benPhoneNum;
	@FXML
	private TextField benEmail;
	@FXML
	private TextField benAccNum;
	@FXML
	private Button btnAddBen;

	
	
	// Event Listener on Button[#btnAddBen].onAction
	@FXML
	public void handeAddBenAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
