package application;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;

public class AddNewBenAnchorPaneController extends Controller implements Initializable {
	@FXML
	private TextField benName;
	@FXML
	private TextField benPhoneNum;
	@FXML
	private TextField benEmail;
	@FXML
	private TextField benAccNum;
	@FXML
	private Button btnAddBen;

	
	
	// Event Listener on Button[#btnAddBen].onAction
	@FXML
	public void handeAddBenAction(ActionEvent event) {
		// TODO Autogenerated
	}



	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
