package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.input.InputMethodEvent;

public class AddNewBenAnchorPaneController {
	@FXML
	private TextField benName;
	@FXML
	private TextField benPhoneNum;
	@FXML
	private TextField benEmail;
	@FXML
	private TextField benAccNum;
	@FXML
	private Button btnAddBen;

	// Event Listener on TextField[#benName].onInputMethodTextChanged
	@FXML
	public void validateBenName(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#benPhoneNum].onInputMethodTextChanged
	@FXML
	public void validateBenPhoneNum(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#benEmail].onInputMethodTextChanged
	@FXML
	public void validateBenEmail(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#benAccNum].onInputMethodTextChanged
	@FXML
	public void validateBenAccNum(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAddBen].onAction
	@FXML
	public void handeAddBenAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
