package application;

import java.io.IOException;
import java.net.URL;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.stream.Collectors;

import dao.CreditCardsDAO;
import dao.TransactionsDAO;
import enums.TransactionType;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.Pane;
import models.CreditCard;
import models.Transaction;

public class CardTransactionsAnchorPaneController extends Controller implements Initializable {
	@FXML
	private Pane paneCards;
	@FXML
	private ComboBox<String> cbCards;
	@FXML
	private Button btnResetCardCBValue;
	@FXML
	private Label lblTotalCardLimit;
	@FXML
	private Label lblRemCardLimit;
	@FXML
	private Label lblTotCardLimitValue;
	@FXML
	private Label lblRemCardLimitValue;
	@FXML
	private TableView<Transaction> tblCards;
	@FXML
	private TableColumn<Transaction, String> tblClmTID;
	@FXML
	private TableColumn<Transaction, Long> tblClmCardNum;
	@FXML
	private TableColumn<Transaction, String> tblClmTName;
	@FXML
	private TableColumn<Transaction, String> tblClmTType;
	@FXML
	private TableColumn<Transaction, Date> tblClmTDate;
	@FXML
	private TableColumn<Transaction, Double> tblClmAmt;

	@FXML
	public void displayCards(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String selectedCardNumber = cbCards.getSelectionModel().getSelectedItem();
		if(selectedCardNumber != null) {
			lblTotalCardLimit.setVisible(true);
			lblTotCardLimitValue.setVisible(true);
			lblRemCardLimit.setVisible(true);
			lblRemCardLimitValue.setVisible(true);
			tblCards.setVisible(true);
			btnResetCardCBValue.setVisible(true);
			
			System.out.println(selectedCardNumber);
			CreditCard userCreditCard = 
					CreditCardsDAO
					.getCreditCardByUserId(user.getUserId().toString());
			lblTotCardLimitValue.setText(userCreditCard.getTotalCreditLimit() + "");
			lblRemCardLimitValue.setText(userCreditCard.getRemainingCreditLimit() + "");
			
			refreshState();
			List<Transaction> cardTransactions = 
					TransactionsDAO
					.getUserTransactions(user.getUserId().toString())
					.stream().filter(transaction -> 
						transaction.getTransactionType() == 
						TransactionType.CARD_TRANSACTION)
					.collect(Collectors.toList());
		        
			ObservableList<Transaction> transactions = 
		        		FXCollections.observableArrayList(cardTransactions);
					
			tblClmTID.setCellValueFactory(new PropertyValueFactory<>("TransactionId"));
			tblClmCardNum.setCellValueFactory(new PropertyValueFactory<>("CardNumber"));
			tblClmTName.setCellValueFactory(new PropertyValueFactory<>("TransactionName"));
			tblClmAmt.setCellValueFactory(new PropertyValueFactory<>("Amount"));
			tblClmTType.setCellValueFactory(new PropertyValueFactory<>("TransactionType"));
			tblClmTDate.setCellValueFactory(new PropertyValueFactory<>("CreatedAt"));
			tblCards.setItems(transactions);
		}
		
	}
	// Event Listener on Button[#btnResetCardCBValue].onAction
	@FXML
	public void clearSelectedValueCardsCB(ActionEvent event) throws IOException {
		// TODO Autogenerated
		cbCards.getSelectionModel().clearSelection();
		cbCards.setButtonCell(new PromptButtonCell<>(cbCards.getPromptText()));
		lblTotalCardLimit.setVisible(false);
		lblTotCardLimitValue.setVisible(false);
		lblRemCardLimit.setVisible(false);
		lblRemCardLimitValue.setVisible(false);
		tblCards.setVisible(false);
		btnResetCardCBValue.setVisible(false);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		//List of card numbers of current user
		CreditCard userCreditCard = CreditCardsDAO
				.getCreditCardByUserId(user.getUserId().toString());
		ObservableList<String> cardNumbersList = 
				FXCollections
				.observableArrayList(userCreditCard.getCardNumber() + "");
		
		//initializing values of account transactions
		cbCards.setItems(cardNumbersList);
		
		//initializing values of card transactions
		cbCards.getSelectionModel().clearSelection();
		lblTotalCardLimit.setVisible(false);
		lblTotCardLimitValue.setVisible(false);
		lblRemCardLimit.setVisible(false);
		lblRemCardLimitValue.setVisible(false);
		tblCards.setVisible(false);
		btnResetCardCBValue.setVisible(false);
	}
}
