package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.layout.Pane;

import javafx.scene.control.TableColumn;

public class CardTransactionsAnchorPaneController extends Controller implements Initializable {
	@FXML
	private Pane paneCards;
	@FXML
	private ComboBox<String> cbCards;
	@FXML
	private Button btnResetCardCBValue;
	@FXML
	private Label lblTotalCardLimit;
	@FXML
	private Label lblRemCardLimit;
	@FXML
	private Label lblTotCardLimitValue;
	@FXML
	private Label lblRemCardLimitValue;
	@FXML
	private TableView<String> tblCards;
	@FXML
	private TableColumn<String, String> tblAccountsClmSNo;
	@FXML
	private TableColumn<String, String> tblCardsClmTID;
	@FXML
	private TableColumn<String, String> tblCardsClmAccNo;
	@FXML
	private TableColumn<String, String> tblCardsClmTName;
	@FXML
	private TableColumn<String, String> tblCardsClmTType;
	@FXML
	private TableColumn<String, String> tblCardsClmTDate;

	@FXML
	public void displayCards(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String selectedValue = cbCards.getSelectionModel().getSelectedItem();
		if(selectedValue != null) {
			lblTotalCardLimit.setVisible(true);
			lblTotCardLimitValue.setVisible(true);
			lblRemCardLimit.setVisible(true);
			lblRemCardLimitValue.setVisible(true);
			tblCards.setVisible(true);
			btnResetCardCBValue.setVisible(true);
		}
		System.out.println(selectedValue);
	}
	// Event Listener on Button[#btnResetCardCBValue].onAction
	@FXML
	public void clearSelectedValueCardsCB(ActionEvent event) throws IOException {
		// TODO Autogenerated
		cbCards.getSelectionModel().clearSelection();
		cbCards.setButtonCell(new PromptButtonCell<>(cbCards.getPromptText()));
		lblTotalCardLimit.setVisible(false);
		lblTotCardLimitValue.setVisible(false);
		lblRemCardLimit.setVisible(false);
		lblRemCardLimitValue.setVisible(false);
		tblCards.setVisible(false);
		btnResetCardCBValue.setVisible(false);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		//List of card numbers of current user
		ObservableList<String> cardNumbersList = 
				FXCollections
				.observableArrayList("5098394467845362", "6573278546789012");
		
		//initializing values of account transactions
		cbCards.setItems(cardNumbersList);
		
		//initializing values of card transactions
		cbCards.getSelectionModel().clearSelection();
		lblTotalCardLimit.setVisible(false);
		lblTotCardLimitValue.setVisible(false);
		lblRemCardLimit.setVisible(false);
		lblRemCardLimitValue.setVisible(false);
		tblCards.setVisible(false);
		btnResetCardCBValue.setVisible(false);
	}
}
