package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.VBox;

public class DepositAnchorPaneController extends Controller implements Initializable {
	@FXML
	private VBox vBoxDeposit;
	@FXML
	private ComboBox<String> cbAccounts;
	@FXML
	private TextField txtAmount;
	@FXML
	private Button btnDeposit;
 
	// Event Listener on ComboBox[#cbAccounts].onAction
	@FXML
	public void displayAccounts(ActionEvent event) {
		// TODO Autogenerated
		
		
		
	}
	// Event Listener on TextField[#txtAmount].onInputMethodTextChanged
	
	// Event Listener on Button[#btnDeposit].onAction
	@FXML
	public void handleDeposit(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
