package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.util.ArrayList;
import java.util.List;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.input.InputMethodEvent;

import javafx.scene.layout.VBox;

public class DepositAnchorPaneController {
	@FXML
	private VBox vBoxDeposit;
	@FXML
	private ComboBox<String> cbAccounts;
	@FXML
	private TextField txtAmount;
	@FXML
	private Button btnDeposit;
 
	// Event Listener on ComboBox[#cbAccounts].onAction
	@FXML
	public void displayAccounts(ActionEvent event) {
		// TODO Autogenerated
		
		List<String> list = //comes from backend
		
	}
	// Event Listener on TextField[#txtAmount].onInputMethodTextChanged
	
	// Event Listener on Button[#btnDeposit].onAction
	@FXML
	public void handleDeposit(ActionEvent event) {
		// TODO Autogenerated
	}
}
