package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.input.InputMethodEvent;
import javafx.scene.control.Hyperlink;

public class LoginSceneController {
	@FXML
	private Label lblBankName;
	@FXML
	private TextField txtEmailLogin;
	@FXML
	private PasswordField txtPasswordLogin;
	@FXML
	private Button btnLogin;
	@FXML
	private Label lblSwitchToRegister;
	@FXML
	private Hyperlink hyperlinkToRegister;

	// Event Listener on TextField[#txtEmailLogin].onInputMethodTextChanged
	@FXML
	public void handleInputEmailChange(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on PasswordField[#txtPasswordLogin].onInputMethodTextChanged
	@FXML
	public void handleInputPasswordChange(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void handleLoginAction(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Map<String, Object> userCredentials = new HashMap<>();
		userCredentials.put("email", txtEmailLogin.getText());
		userCredentials.put("password", txtPasswordLogin.getText());
		SwitchSceneController.invokeLayout(event, SceneFiles.HOME_SCENE_LAYOUT);
	}
	// Event Listener on Hyperlink[#hyperlinkToRegister].onAction
	@FXML
	public void handleSwitchToRegisterScene(ActionEvent event) throws IOException {
		// TODO Autogenerated
		SwitchSceneController.invokeLayout(event, SceneFiles.REGISTER_SCENE_LAYOUT);
	}
}
