package application;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import dao.UsersDAO;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Hyperlink;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import models.User;
import services.UserService;
import utils.UserUtils;
import validations.UserValidations;

public class LoginSceneController {
	@FXML
	private Label lblBankName;
	@FXML
	private TextField txtEmailLogin;
	@FXML
	private PasswordField txtPasswordLogin;
	@FXML
	private Button btnLogin;
	@FXML
	private Label lblSwitchToRegister;
	@FXML
	private Hyperlink hyperlinkToRegister;

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void handleLoginAction(ActionEvent event) throws IOException {

		String title = null;
		String headerText = null;
		String contentText = null;

		// TODO Autogenerated
		String email = txtEmailLogin.getText();
		String password = txtPasswordLogin.getText();

		boolean isEmailValid = UserValidations.isEmailValid(email);
		boolean isPasswordValid = UserValidations.isPasswordValid(password);

		if (!isEmailValid || !isPasswordValid) {
			if (!isEmailValid) {
				headerText = "Invalid Email";
				AlertController.showError(title, headerText, contentText);
				return;
			}

			if (!isPasswordValid) {
				headerText = "Invalid Password";
				AlertController.showError(title, headerText, contentText);
				return;
			}
		} else {
			// check whether user exists
			boolean userExists = UsersDAO.userExistsByEmail(email);
			if (!userExists) {
				title = "Login";
				headerText = "User does not exist with given email";
				AlertController.showError(title, headerText, contentText);
				return;
			} else {
				boolean isValidEmailPassword = UserUtils.isEmailPasswordValid(email, password);
				if (isValidEmailPassword) {
					SwitchSceneController.invokeLayout(event, SceneFiles.HOME_SCENE_LAYOUT);
				} else {
					title = "Login";
					headerText = "Email and Password Does Not Match";
					AlertController.showError(title, headerText, contentText);
					return;
				}
			}
		}
	}

	// Event Listener on Hyperlink[#hyperlinkToRegister].onAction
	@FXML
	public void handleSwitchToRegisterScene(ActionEvent event) throws IOException {
		// TODO Autogenerated
		SwitchSceneController.invokeLayout(event, SceneFiles.REGISTER_SCENE_LAYOUT);
	}
}
