package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.input.InputMethodEvent;

public class PayBySavingsAnchorPaneController implements Initializable {
	@FXML
	private ComboBox<String> cbAccounts;
	@FXML
	private TextField txtAmount;
	@FXML
	private Button btnPayBySavings;
	@FXML
	private Button btnReset;
	
	public void handleReset(ActionEvent event) {
		// TODO Autogenerated
		btnReset.setVisible(false);
		cbAccounts.getSelectionModel().clearSelection();
		cbAccounts.setButtonCell(new PromptButtonCell<>(cbAccounts.getPromptText()));
		txtAmount.setText("");
		txtAmount.setVisible(false);
		btnPayBySavings.setVisible(false);
	}
	// Event Listener on ComboBox[#cbAccounts].onAction
	@FXML
	public void displayAccounts(ActionEvent event) {
		// TODO Autogenerated
		String selectedValue = cbAccounts.getSelectionModel().getSelectedItem();
		if(selectedValue != null) {
			btnReset.setVisible(true);
			txtAmount.setVisible(true);
			txtAmount.setText("");
			btnPayBySavings.setVisible(true);
		}
	}

	// Event Listener on Button[#btnPayBySavings].onAction
	@FXML
	public void handlePayBySavings(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		ObservableList<String> accountNumbersList = 
				FXCollections.observableArrayList("94467845362", "78546789012");
		cbAccounts.setItems(accountNumbersList);
		btnReset.setVisible(false);
		txtAmount.setText("");
		txtAmount.setVisible(false);
		btnPayBySavings.setVisible(false);
	}
}
