package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.input.InputMethodEvent;

public class PayByCreditAnchorPaneController implements Initializable {
	@FXML
	private ComboBox<String> cbCards;
	@FXML
	private TextField txtAmount;
	@FXML
	private Button btnPayByCredit;
	@FXML
	private Button btnReset;
	// Event Listener on ComboBox[#cbCards].onAction
	@FXML
	public void displayCards(ActionEvent event) {
		// TODO Autogenerated
		String selectedValue = cbCards.getSelectionModel().getSelectedItem();
		if(selectedValue != null) {
			btnReset.setVisible(true);
			txtAmount.setVisible(true);
			txtAmount.setText("");
			btnPayByCredit.setVisible(true);
		}
	}
	// Event Listener on TextField[#txtAmount].onInputMethodTextChanged
	@FXML
	public void validateAmount(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPayByCredit].onAction
	@FXML
	public void handlePayByCredit(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void handleReset(ActionEvent event) {
		// TODO Autogenerated
		btnReset.setVisible(false);
		cbCards.getSelectionModel().clearSelection();
		cbCards.setButtonCell(new PromptButtonCell<>(cbCards.getPromptText()));;
		txtAmount.setText("");
		txtAmount.setVisible(false);
		btnPayByCredit.setVisible(false);
	}/////
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		ObservableList<String> cardNumbersList = 
				FXCollections
				.observableArrayList("5098394467845362", "6573278546789012");
		
		//initializing values of account transactions
		cbCards.setItems(cardNumbersList);
		
		txtAmount.setText("");
		txtAmount.setVisible(false);
		btnPayByCredit.setVisible(false);
		btnReset.setVisible(false);
	}
}
