package application;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

public class ProfileInfoSceneController {
	@FXML
	private Label lblHome;
	@FXML
	private Button btnLogout;
	@FXML
	private Label lblCurrentUserEmail;
	@FXML
	private Button btnGoBack;
	@FXML
	private Label lblName;
	@FXML
	private TextField txtName;
	@FXML
	private Label lblEmail;
	@FXML
	private TextField txtEmail;
	@FXML
	private Label lblPhone;
	@FXML
	private TextField txtPhone;
	@FXML
	private Button btnChangePassword;
	@FXML
	private Button btnChangeNumber;

	// Event Listener on Button[#btnLogout].onAction
	@FXML
	public void handleLogoutAction(ActionEvent event) throws IOException {
		// TODO Autogenerated
		SwitchSceneController.invokeLayout(event, SceneFiles.LOGIN_SCENE_LAYOUT);
	}
	@FXML
	public void invokeHomeSceneLayout(ActionEvent event) throws IOException {
		// TODO Autogenerated
		SwitchSceneController.invokeLayout(event, SceneFiles.HOME_SCENE_LAYOUT);
	}
	// Event Listener on Button[#btnChangePassword].onAction
	@FXML
	public void triggerConfirmationDialog(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnChangeNumber].onAction
	@FXML
	public void triggerOTPVerificationDialog(ActionEvent event) {
		// TODO Autogenerated
	}
}
