package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;

import javax.mail.MessagingException;

import dao.UsersDAO;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.input.InputMethodEvent;
import javafx.stage.Stage;
import models.SavingsAccount;
import models.User;
import notifications.EmailService;
import services.SavingsAccountService;
import services.UserService;
import utils.PasswordUtils;
import utils.TransactionUtils;
import utils.UserUtils;
import validations.UserValidations;
import javafx.scene.control.Hyperlink;

public class RegisterSceneController implements Initializable {
	@FXML
	private Label lblBankName;
	@FXML
	private TextField txtEmail;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private Button btnRegister;
	@FXML
	private Hyperlink hyperlinkToLogin;
	@FXML
	private Label lblSwitchToLogin;
	@FXML
	private TextField txtName;
	@FXML
	private TextField txtPhone;

	private static final String LOGIN_SCENE_LAYOUT = "LoginScene.fxml";

	// Event Listener on Button[#btnRegister].onAction
	@FXML
	public void handleRegisterAction(ActionEvent event) throws IOException, MessagingException {
		// TODO Autogenerated

		String title = null;
		String headerText = null;
		String contentText = null;

		title = "Create New User";

		String name = txtName.getText();
		String email = txtEmail.getText();
		String password = txtPassword.getText();
		String phone = txtPhone.getText();

		boolean isEmailValid = UserValidations.isEmailValid(email);
		boolean isPasswordValid = UserValidations.isPasswordValid(password);
		boolean isPhoneValid = UserValidations.isPhoneValid(phone);
		boolean isNameValid = UserValidations.isNameValid(name);

		if (!isEmailValid || !isPasswordValid || !isPhoneValid || !isNameValid) {
			if (!isEmailValid) {
				headerText = "Invalid Email";
				AlertController.showError(title, headerText, contentText);
				return;
			}

			if (!isPasswordValid) {
				headerText = "Invalid Password";
				AlertController.showError(title, headerText, contentText);
				return;
			}

			if (!isPhoneValid) {
				headerText = "Invalid Phone";
				AlertController.showError(title, headerText, contentText);
				return;
			}

			if (!isNameValid) {
				headerText = "Invalid Name Format";
				AlertController.showError(title, headerText, contentText);
				return;
			}
		} else {

			long phoneNumber = Long.parseLong(phone);
			boolean phoneExists = UsersDAO.userExistsByPhone(phoneNumber);
			boolean emailExists = UsersDAO.userExistsByEmail(email);
			if (phoneExists) {
				headerText = "Phone Number Already Exists";
				AlertController.showError(title, headerText, contentText);
				return;
			} 
			if (emailExists) {
				headerText = "Email Already Exists";
				AlertController.showError(title, headerText, contentText);
				return;
			} 
			else {
				String hashPassword = PasswordUtils.hashPassword(password);

				Map<String, Object> userData = new HashMap<>();
				userData.put("name", name);
				userData.put("password", hashPassword);
				userData.put("phone", phone);
				userData.put("email", email);

				User user = UserService.findOrCreateUser(userData);
				SavingsAccountService.createSavingsAccount(user.getUserId().toString(), user);

				headerText = "Created user and savings account successfully";
				AlertController.showConfirmation(title, headerText, contentText);
				return;
			}
		}
	}

	// Event Listener on Hyperlink[#hyperlinkToLogin].onAction
	@FXML
	public void handleSwitchToLoginScene(ActionEvent event) throws IOException {
		// TODO Autogenerated
		SwitchSceneController.invokeLayout(event, LOGIN_SCENE_LAYOUT);
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub

	}

}
