package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.input.InputMethodEvent;
import javafx.scene.control.Hyperlink;

public class RegisterSceneController {
	@FXML
	private Label lblBankName;
	@FXML
	private TextField txtEmail;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private Button btnRegister;
	@FXML
	private Hyperlink hyperlinkToLogin;
	@FXML
	private Label lblSwitchToLogin;
	@FXML
	private TextField txtName;
	@FXML
	private TextField txtPhone;
	
	private static final String LOGIN_SCENE_LAYOUT = "LoginScene.fxml";

	
	// Event Listener on Button[#btnRegister].onAction
	@FXML
	public void handleRegisterAction(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
	}
	// Event Listener on Hyperlink[#hyperlinkToLogin].onAction
	@FXML
	public void handleSwitchToLoginScene(ActionEvent event) throws IOException {
		// TODO Autogenerated
		SwitchSceneController.invokeLayout(event, LOGIN_SCENE_LAYOUT);
	}

}
