package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.input.InputMethodEvent;
import javafx.stage.Stage;
import models.SavingsAccount;
import models.User;
import services.SavingsAccountService;
import services.UserService;
import javafx.scene.control.Hyperlink;

public class RegisterSceneController implements Initializable {
	@FXML
	private Label lblBankName;
	@FXML
	private TextField txtEmail;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private Button btnRegister;
	@FXML
	private Hyperlink hyperlinkToLogin;
	@FXML
	private Label lblSwitchToLogin;
	@FXML
	private TextField txtName;
	@FXML
	private TextField txtPhone;
	
	private static final String LOGIN_SCENE_LAYOUT = "LoginScene.fxml";

	
	// Event Listener on Button[#btnRegister].onAction
	@FXML
	public void handleRegisterAction(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String name = txtName.getText();
		String email =txtEmail.getText();
		String password = txtPassword.getText();
		String phone = txtPhone.getText();
		
		Map<String,Object> userData= new HashMap<>();
		userData.put("name", name);
		userData.put("password", password);
		userData.put("phone", phone);
		userData.put("email", email);
		
		User user = UserService.findOrCreateUser(userData);
		SavingsAccountService.createSavingsAccount(user.getUserId().toString(), user);
		
		
	}
	// Event Listener on Hyperlink[#hyperlinkToLogin].onAction
	@FXML
	public void handleSwitchToLoginScene(ActionEvent event) throws IOException {
		// TODO Autogenerated
		SwitchSceneController.invokeLayout(event, LOGIN_SCENE_LAYOUT);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
		
	}

}
