package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.input.InputMethodEvent;

import javafx.scene.layout.VBox;

public class TransferToSelfAnchorPaneController {
	@FXML
	private VBox vBoxTransferToSelf;
	@FXML
	private ComboBox<String> cbFromAccount;
	@FXML
	private ComboBox<String> cbToAccount;
	@FXML
	private TextField txtAmount;
	@FXML
	private Button btnTransfer;

	// Event Listener on ComboBox[#cbFromAccount].onAction
	@FXML
	public void displayFromAccounts(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cbToAccount].onAction
	@FXML
	public void displayToAccounts(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#txtAmount].onInputMethodTextChanged
	@FXML
	public void validateAmount(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnTransfer].onAction
	@FXML
	public void handleTransfer(ActionEvent event) {
		// TODO Autogenerated
	}
}
