package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ToggleGroup;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.RadioButton;

public class TransferOtherAnchorPaneController implements Initializable {
	@FXML
	private RadioButton radioBtnBenifExist;
	@FXML
	private ToggleGroup beneficiaryTransferOptions;
	@FXML
	private RadioButton radioBtnBenifNew;
	@FXML
	private AnchorPane anchorPane;

	// Event Listener on RadioButton.onAction
	@FXML
	public void handleBeneficiaryTransferOptions(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
